# fly.toml app configuration file generated for omnistrate-blog-prod on 2025-10-31T18:10:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omnistrate-blog-prod'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[deploy]
  strategy = 'canary'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 30
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '2s'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
