name: Release

on:
  release:
    types: ["published"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/fly-deploy.yml
    secrets: inherit
    with:
      environment: dev

  deploy-to-prod:
    name: Deploy to Prod
    needs: deploy-to-prod-shadow
    uses: ./.github/workflows/fly-deploy.yml
    secrets: inherit
    with:
      environment: prod

  # notification:
  #   name: Notify Mattermost
  #   runs-on: ubuntu-latest
  #   needs: deploy-to-prod
  #   steps:
  #     - name: Mattermost Notification
  #       uses: tferreira/matterfy@v1.9
  #       with:
  #         type: ${{ job.status }}
  #         job_name: "*Deploy to Prod*"
  #         url: ${{ secrets.MATTERMOST_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
